# 仅仅在如下4种情况下才会抛出异常

1）调用了一个会抛出“已检查异常”的方法；
2）程序运行过程中发生了错误，并且用throw语句抛出一个“已检查异常”；
3）程序错误，如数组下标越界；
4）Java虚拟机或者运行时库出现了内部错误；
如果是出现头两种情况，就必须告诉那些会调用该方法的程序员：如果调用该方法，可能会抛出异常。因为任何抛出异常的方法都可能是一个死亡陷阱，如果没有合适的异常处理器来捕获这些异常，则当前线程会被终止。